#version 450

#define MAX_CHUNK_BUFFER_SIZE 0x10
#define AREA 9*9
#define MAX_PARTICLE_BRUH 4
#define BALLS_SIZE 1.5
#define BALLS_FORCE 10

layout(local_size_x = AREA) in;

struct ParticleData {
    vec3 position;
	uint connectionsOffset;
    vec3 velocity;
	uint connectionsCount;
	vec3 originalPos;
	float unused;
};

struct PParticleData {
    vec3 position;
	uint connectionsOffset;
    vec3 velocity;
	uint connectionsCount;
	vec3 originalPos;
	uint connectionsLOffset;
	uint connectionsLCount;
	uint _paddingA, _paddingB, _paddingC;
};

struct NeighborData
{
	vec3 pos;
	int offset;
};

struct ChunkData
{
	vec3 chunkPos;
	uint offset;
	uint particleCount;
	uint connectionOffset;
	uint connectionLOffset;
	uint surfacePointsOffset;
	NeighborData neighbors[8];
};

struct ChunkHeader {
	vec3    spherePos;
	float   sphereRadius;
	vec3   gravity;
	float   deltaTime;
	float   damping;
	float   strength;
	uint   _paddingA, _paddingB;
    ChunkData chunks[MAX_CHUNK_BUFFER_SIZE];
};

layout(set = 0, binding = 0) buffer PParticles {
    PParticleData pParticles[];
};

layout(set = 0, binding = 1) buffer Particles {
    ParticleData particles[];
};

layout(set = 0, binding = 2) buffer SurfacePoints {
    uint points[];
};

layout(set = 0, binding = 3) buffer ChunkHeaders {
	ChunkHeader chunkData[];
};

layout(push_constant) uniform Push {
	vec3 meshPos;
    uint bufferOffset;
	uint particleCount;
} pc;

struct CollisionResult
{
	vec3 vel;
	uint id;
};

shared CollisionResult results[AREA*MAX_PARTICLE_BRUH];

void main()
{
    uint id = gl_GlobalInvocationID.x;
	
	uint chunkID = MAX_CHUNK_BUFFER_SIZE;
	uint particleID = 0;
	uint counter = 0;
	for	(uint i = 0; i < MAX_CHUNK_BUFFER_SIZE; i++)
	{
		if (AREA + counter > id)
		{
			chunkID = i;
			particleID = id - counter;
			break;
		}
		counter += AREA;
	}
	
	uint pId = particleID;
	for (uint i = 0; i < MAX_PARTICLE_BRUH; i++)
	{
		results[pId*MAX_PARTICLE_BRUH+i].vel = vec3(0,0,0);
		results[pId*MAX_PARTICLE_BRUH+i].id = pc.particleCount;
	}
	memoryBarrierShared();
	
	particleID = chunkData[pc.bufferOffset].chunks[chunkID].offset + points[chunkData[pc.bufferOffset].chunks[chunkID].surfacePointsOffset + particleID];
    vec3 vel = pParticles[particleID].velocity;
	vec3 pos = pParticles[particleID].position;
	
	// Collide with da softBody
	uint cCounter = 0;
	for	(uint i = 0; i < pc.particleCount; i++)
	{
		vec3 p = particles[i].position + pc.meshPos;
		vec3 AB = p - pos - chunkData[pc.bufferOffset].chunks[chunkID].chunkPos;
		float l = length(AB);
		if (l > BALLS_SIZE || l < 0.00001)
			continue;
		// Ok now we ball
		//AB = normalize(AB);
		pos -= AB * 0.5;
		results[pId*MAX_PARTICLE_BRUH+cCounter].vel = AB * 0.25;
		results[pId*MAX_PARTICLE_BRUH+cCounter].id = i;
		cCounter++;
		//pos = vec3(0,0,0);
		if (cCounter >= MAX_PARTICLE_BRUH)	// Max amount of collisions reached
			break;
	}

    pParticles[particleID].position = pos;
    pParticles[particleID].velocity = vel;
	
	if (pId != 0)
		return;
	
	memoryBarrierShared();
	
	for	(uint i = 0; i < AREA*MAX_PARTICLE_BRUH; i++)
	{
		if (results[i].id >= pc.particleCount)
			continue;
		particles[results[i].id].position += results[i].vel * 0.25;
		particles[results[i].id].velocity += results[i].vel * BALLS_FORCE;
	}
}
