#version 450

#define MAX_CHUNK_BUFFER_SIZE 0x10

layout(local_size_x = 64) in;

struct ParticleData {
    vec3 position;
	uint connectionsOffset;
    vec3 velocity;
	uint connectionsCount;
	vec3 originalPos;
	uint connectionsLOffset;
	uint connectionsLCount;
	uint _paddingA, _paddingB, _paddingC;
};

struct NeighborData
{
	vec3 pos;
	int offset;
};

struct ChunkData
{
	vec3 chunkPos;
	uint offset;
	NeighborData neighbors[8];
	uint particleCount;
	uint connectionOffset;
	uint connectionLOffset;
	uint _padding;
};

layout(set = 0, binding = 0) buffer Particles {
    ParticleData particles[];
};

layout(set = 0, binding = 3) buffer ChunkHeader {
	vec3    spherePos;
	float   sphereRadius;
	vec3   gravity;
	float   deltaTime;
	float   damping;
	float   strength;
	uint   _paddingA, _paddingB;
    ChunkData chunks[MAX_CHUNK_BUFFER_SIZE];
} chunkData;


void main()
{
    uint id = gl_GlobalInvocationID.x;
	
	uint chunkID = MAX_CHUNK_BUFFER_SIZE;
	uint particleID = 0;
	uint counter = 0;
	for	(uint i = 0; i < MAX_CHUNK_BUFFER_SIZE; i++)
	{
		if (chunkData.chunks[i].particleCount + counter > id)
		{
			chunkID = i;
			particleID = chunkData.chunks[i].offset + id - counter;
			break;
		}
		counter += chunkData.chunks[i].particleCount;
	}
	
    if (chunkID == MAX_CHUNK_BUFFER_SIZE)
        return;
	
    vec3 vel = particles[particleID].velocity;
	vec3 pos = particles[particleID].position;
	
	// Collide with sphere
	
	vec3 spPos = chunkData.spherePos - chunkData.chunks[chunkID].chunkPos;
	vec3 ab = spPos - pos;
	
	float f = length(ab);
	if (f <= chunkData.sphereRadius)
	{
		vec3 dif = -normalize(ab) * (chunkData.sphereRadius - f);
		vel += dif * chunkData.strength * 0.01;
		pos += dif;
    }
	pos += vel * chunkData.deltaTime;

    particles[particleID].position = pos;
}
