#version 450

#define MAX_CHUNK_BUFFER_SIZE 0x10

layout(local_size_x = 64) in;

struct ParticleData {
    vec3 position;
	uint connectionsOffset;
    vec3 velocity;
	uint connectionsCount;
	vec3 originalPos;
	uint connectionsLOffset;
	uint connectionsLCount;
	uint _paddingA, _paddingB, _paddingC;
};

struct ConnectionData
{
    uint particleID;
    float initialLength;
};

struct ConnectionDataL
{
	vec3 originalPos;
    uint chunkID;
    uint particleID;
    float initialLength;
	uint _paddingA, _paddingB;
};

struct NeighborData
{
	vec3 pos;
	int offset;
};

struct ChunkData
{
	vec3 chunkPos;
	uint offset;
	NeighborData neighbors[8];
	uint particleCount;
	uint connectionOffset;
	uint connectionLOffset;
	uint _padding;
};

layout(set = 0, binding = 0) buffer Particles {
    ParticleData particles[];
};

layout(set = 0, binding = 1) buffer Connections {
    ConnectionData connections[];
};

layout(set = 0, binding = 2) buffer ConnectionsL {
    ConnectionDataL connectionsL[];
};

layout(set = 0, binding = 3) buffer ChunkHeader {
	vec3    spherePos;
	float   sphereRadius;
	vec3   gravity;
	float   deltaTime;
	float   damping;
	float   strength;
	uint   _paddingA, _paddingB;
    ChunkData chunks[MAX_CHUNK_BUFFER_SIZE];
} chunkData;

void main()
{
    uint id = gl_GlobalInvocationID.x;
	
	uint chunkID = MAX_CHUNK_BUFFER_SIZE;
	uint particleID = 0;
	uint counter = 0;
	for	(uint i = 0; i < MAX_CHUNK_BUFFER_SIZE; i++)
	{
		if (chunkData.chunks[i].particleCount + counter > id)
		{
			chunkID = i;
			particleID = chunkData.chunks[i].offset + id - counter;
			break;
		}
		counter += chunkData.chunks[i].particleCount;
	}
	
    if (chunkID == MAX_CHUNK_BUFFER_SIZE)
        return;
	
    vec3 vel = particles[particleID].velocity;
	vec3 pos = particles[particleID].position;
    
	vel -= chunkData.gravity * chunkData.deltaTime;
	
	const uint cCount = particles[particleID].connectionsCount;
	const uint lCount = particles[particleID].connectionsLCount;
	const uint cOff = particles[particleID].connectionsOffset + chunkData.chunks[chunkID].connectionOffset;
	const uint lOff = particles[particleID].connectionsLOffset + chunkData.chunks[chunkID].connectionLOffset;
	
	if (cCount == 0)
	{
		particles[particleID].velocity = vec3(0);
		return;
	}
	
    for (uint i = 0; i < cCount; i++)
	{
		ConnectionData c = connections[cOff + i];
		vec3 dif = particles[c.particleID].position - pos;
		float f = length(dif) - c.initialLength;
		vel += normalize(dif) * (f * chunkData.deltaTime * chunkData.strength);
	}
	
	for (uint i = 0; i < lCount; i++)
	{
		ConnectionDataL c = connectionsL[cOff + i];
		vec3 dif = chunkData.chunks[c.chunkID].chunkPos - chunkData.chunks[chunkID].chunkPos;
		vec3 ab;
		if (chunkData.chunks[chunkID].neighbors[c.chunkID].offset < 0) // chunk is not present in memory, use to original pos instead
		{
			ab = c.originalPos - dif - pos;
		}
		else
		{
			ab = particles[chunkData.chunks[chunkID].neighbors[c.chunkID].offset + c.particleID].position - dif - pos;
		}
		float f = length(ab) - c.initialLength;
		vel += normalize(ab) * (f * chunkData.deltaTime * chunkData.strength);
	}
	
	vel = vel * max(1 - chunkData.damping * chunkData.deltaTime, 0.05);
	
	float l = length(vel);
	if (l > 10.)
		vel = normalize(vel) * 10.;

    particles[id].velocity = vel;
}
