#version 450

#define MAX_CHUNK_BUFFER_SIZE 0x10

layout(local_size_x = 64) in;

struct ParticleData {
    vec3 position;
	uint connectionsOffset;
    vec3 velocity;
	uint connectionsCount;
	vec3 originalPos;
	uint connectionsLOffset;
	uint connectionsLCount;
	uint _paddingA, _paddingB, _paddingC;
};

struct ConnectionData
{
    uint particleID;
    float initialLength;
};

struct ConnectionDataL
{
	vec3 originalPos;
    uint chunkID;
    uint particleID;
    float initialLength;
	uint _paddingA, _paddingB;
};

struct NeighborData
{
	vec3 pos;
	int offset;
};

struct ChunkData
{
	vec3 chunkPos;
	uint offset;
	uint particleCount;
	uint connectionOffset;
	uint connectionLOffset;
	uint _padding;
	NeighborData neighbors[8];
};

struct ChunkHeader {
	vec3    spherePos;
	float   sphereRadius;
	vec3   gravity;
	float   deltaTime;
	float   damping;
	float   strength;
	uint   _paddingA, _paddingB;
    ChunkData chunks[MAX_CHUNK_BUFFER_SIZE];
};

layout(set = 0, binding = 0) buffer Particles {
    ParticleData particles[];
};

layout(set = 0, binding = 1) buffer Connections {
    ConnectionData connections[];
};

layout(set = 0, binding = 2) buffer ConnectionsL {
    ConnectionDataL connectionsL[];
};

layout(set = 0, binding = 3) buffer ChunkHeaders {
	ChunkHeader chunkData[];
};

layout(push_constant) uniform Push {
    uint bufferOffset;
} pc;


void main()
{
    uint id = gl_GlobalInvocationID.x;
	
	uint chunkID = MAX_CHUNK_BUFFER_SIZE;
	uint particleID = 0;
	uint particleBufStart = 0;
	uint counter = 0;
	for	(uint i = 0; i < MAX_CHUNK_BUFFER_SIZE; i++)
	{
		uint pCount = chunkData[pc.bufferOffset].chunks[i].particleCount;
		if (pCount + counter > id)
		{
			chunkID = i;
			particleBufStart = chunkData[pc.bufferOffset].chunks[i].offset;
			particleID = particleBufStart - counter + id;
			break;
		}
		counter += pCount;
	}
	
    if (chunkID == MAX_CHUNK_BUFFER_SIZE)
        return;
	
	const uint cCount = particles[particleID].connectionsCount;
	const uint lCount = particles[particleID].connectionsLCount;
	const uint cOff = particles[particleID].connectionsOffset + chunkData[pc.bufferOffset].chunks[chunkID].connectionOffset;
	const uint lOff = particles[particleID].connectionsLOffset + chunkData[pc.bufferOffset].chunks[chunkID].connectionLOffset;
	
	if (cCount == 0)
	{
		particles[particleID].velocity = vec3(0);
		return;
	}
	
	vec3 vel = particles[particleID].velocity;
	vec3 pos = particles[particleID].position;
    
	vel -= chunkData[pc.bufferOffset].gravity * chunkData[pc.bufferOffset].deltaTime;
	
    for (uint i = 0; i < cCount; i++)
	{
		ConnectionData c = connections[cOff + i];
		vec3 dif = particles[c.particleID + particleBufStart].position - pos;
		float l = length(dif);
		if (l > 0.001)
			vel += normalize(dif) * ((l - c.initialLength) * chunkData[pc.bufferOffset].deltaTime * chunkData[pc.bufferOffset].strength);
	}
	
	for (uint i = 0; i < lCount; i++)
	{
		ConnectionDataL c = connectionsL[cOff + i];
		vec3 dif = chunkData[pc.bufferOffset].chunks[chunkID].neighbors[c.chunkID].pos - chunkData[pc.bufferOffset].chunks[chunkID].chunkPos;
		vec3 ab;
		int nbOffset = chunkData[pc.bufferOffset].chunks[chunkID].neighbors[c.chunkID].offset;
		if (nbOffset < 0) // chunk is not present in buffer, use original pos instead
		{
			ab = c.originalPos - pos - dif;
			
			vel = vec3(0);
			break;
		}
		else
		{
			ab = particles[c.particleID + nbOffset].position - pos - dif;
		}
		float l = length(ab);
		if (l > 0.001)
			vel += normalize(ab) * ((l - c.initialLength) * chunkData[pc.bufferOffset].deltaTime * chunkData[pc.bufferOffset].strength);
	}
	
	vel = vel * max(1 - chunkData[pc.bufferOffset].damping * chunkData[pc.bufferOffset].deltaTime, 0.05);
	
	float l = length(vel);
	if (l > 10.)
		vel = normalize(vel) * 10.;

    //particles[particleID].velocity = vel;
    particles[particleID].velocity = vel;
}
